<?php
return array (
  7 => 
  array (
    'id' => '7',
    'catid' => '32',
    'typeid' => '0',
    'title' => '中住蓝，不一样的蓝',
    'style' => '',
    'thumb' => 'http://www.zhongzhudichan.com/uploadfile/2020/0811/20200811011647140.png',
    'keywords' => '',
    'description' => '中住蓝，不一样的蓝中住蓝，不一样的蓝中住蓝，不一样的蓝中住蓝，不一样的蓝 中住蓝，不一样的蓝中住蓝，不一样的蓝中住蓝，不一样的蓝中   ',
    'posids' => '0',
    'url' => 'http://localhost:22024/index.php?m=content&c=index&a=show&catid=32&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1596852077',
    'updatetime' => '1596852162',
    'hitsid' => 'c-1-7',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '32',
    'typeid' => '0',
    'title' => '视频首页每日热点',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '视频首页每日热点视频首页每日热点视频首页每日热点视频首页每日热点视频首页每日热点视频首页每日热点视频首页每日热点视频首页每日热点视   ',
    'posids' => '0',
    'url' => 'http://www.zhongzhudichan.com/index.php?m=content&c=index&a=show&catid=32&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1596855884',
    'updatetime' => '1596855888',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>