<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业使命',
    'style' => '',
    'thumb' => 'http://www.zhongzhudichan.com/uploadfile/2020/0811/20200811013050171.png',
    'keywords' => '',
    'description' => '成为中国最卓越的不动产综合服务提供商',
    'posids' => '0',
    'url' => 'http://www.zhongzhudichan.com/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1596701034',
    'updatetime' => '1596701048',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业价值观',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '价值观：利他客户需求至上，团队利益为先，利他才能利己。 合作目标一致、勇于担当、齐心协力、彼此配合。 宽容多用审视的眼光看自己，多   ',
    'posids' => '0',
    'url' => 'http://localhost:22022/index.php?m=content&c=index&a=show&catid=13&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1596701055',
    'updatetime' => '1596701061',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业愿景',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '员工幸福：打造赋能型平台，创造员工精神物质双丰收 客户感动：洞察客户心理与实质需求，提供超期望值服务 行业发展：严守法律法规，以身   ',
    'posids' => '0',
    'url' => 'http://www.zhongzhudichan.com/index.php?m=content&c=index&a=show&catid=13&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1596701068',
    'updatetime' => '1596701074',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>